name: setup

description: Installs the rust toolchain.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: restore cache
      uses: actions/cache@v4
      id: toolchain-cache
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target/
        key: v3::rust-toolchain::${{ runner.os }}::${{ hashFiles('**/Cargo.lock', 'rust-toolchain.toml', '.github/actions/setup/action.yml') }}

    - name: install rust toolchain
      if: steps.toolchain-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        rustup update
        cargo install wasm-opt
