name: setup

description: Installs the rust toolchain.

inputs:
  wasm-opt:
    description: "Build wasm-opt"
    type: boolean
    required: true
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: restore cache
      uses: actions/cache@v4
      id: toolchain-cache
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target/
        key: v4::rust-toolchain::${{ runner.os }}::${{ hashFiles('**/Cargo.lock', 'rust-toolchain.toml', '.github/actions/setup/action.yml') }}::${{ inputs.wasm-opt }}

    - name: install rust toolchain
      if: steps.toolchain-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        rustup update

    - name: build wasm-opt
      if: steps.toolchain-cache.outputs.cache-hit != 'true' && inputs.wasm-opt == 'true'
      shell: bash
      run: |
        cargo install wasm-opt
