_format_version: "3.0"

services:
- name: demo
  url: http://httpbin.konghq.com
  routes:
  - name: my-route
    paths:
    - /anything
    strip_path: false
    methods:
    - GET
    - POST
    filter_chains:
    - filters:
      - name: datakit
        config:
          debug: true
          nodes:
          - name: FIRST
            type: call
            url: https://api.zippopotam.us/br/93000-000
          - name: MY_HEADERS
            type: jq
            inputs:
            - first: FIRST.body
            output: service_request.headers
            jq: |
              {
                "X-Hello": "World",
                "X-Foo": "Bar",
                "X-Name": "{{ first.country }}"
              }
          - name: MY_BODY
            type: handlebars
            content_type: text/plain
            inputs:
            - first: FIRST.body
            output: service_request.body
            template: |
              Coordinates for {{ first.places.0.[place name] }}, {{ first.places.0.state }}, {{ first.country }} are ({{ first.places.0.latitude }}, {{ first.places.0.longitude }}).
