_format_version: "3.0"
services:
- url: http://httpbin.konghq.com
  name: my-service
  routes:
  - name: my-route
    paths:
    - /
    strip_path: true
  filter_chains:
    - filters:
      - name: datakit
        config:
          debug: true
          nodes:
          - name: JOIN
            type: jq
            inputs:
            - req: request.headers
            jq: |
              {
                "key": $req.foo
              }
          - name: EXIT
            type: exit
            inputs:
            - body: JOIN
            status: 200
